# feeder
feeder: feeders.feeder_dhg14_28.Feeder
train_feeder_args:
  data_path: joint  #  joint, bone, motion, bone motion
  label_path: train 
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 150 # max
  normalization: False
  repeat: 5 
  label_flag: 14 # 14 or 28
  idx: 14 # index for different people

test_feeder_args:
  data_path: joint 
  label_path: val 
  debug: False
  random_choose: False
  idx: 14 # index for different people
  label_flag: 14 # 14 or 28

# model
model: model.tdgcn.Model
model_args:
  num_class: 14 #  14 or 28
  num_point: 22 
  num_person: 1
  graph: graph.dhg14_28.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001 
base_lr: 0.1  
lr_decay_rate: 0.1 
step: [90, 130] # [90, 130]

# training
device: 4
batch_size: 32 # 32
test_batch_size: 32 # 32
num_epoch: 150 # 150
nesterov: True
warm_up_epoch: 20 # 20

work_dir: ./work_dir/dhg14-28/14joint_14